[workspace]
# Todo: dist is building a bunch of crates that should not be needed for the CLI (e.g. the wasm integration)
members = ["cargo:tools/oicana_cli"]

# Config for 'dist'
[dist]
crates = ["oicana_cli"]
# A prefix git tags must include for dist to care about them
tag-namespace = "oicana_cli"
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
allow-dirty = ["ci"]
# vendor open ssl for linux builds
features = ["vendor-openssl"]

[dist.github-custom-runners]
global = "ubuntu-22.04"
aarch64-apple-darwin = "macos-14"
x86_64-apple-darwin = "macos-13"
x86_64-pc-windows-msvc = "windows-latest"
x86_64-unknown-linux-gnu = "ubuntu-22.04"
aarch64-pc-windows-msvc = "windows-latest"
