[build]
command = "rustup default stable && curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash && cargo binstall --git https://github.com/Myriad-Dreamin/shiroa --tag v0.3.1-rc3 shiroa && shiroa build --mode static-html --workspace .."
publish = "dist"