[package]
name = "oicana-python-native"
version = "0.9.0-rc.1"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license-file = "LICENSE.md"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
name = "oicana_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29.0", features = ["extension-module", "abi3-py38", "hashbrown"] }

oicana_ffi_core = { workspace = true }

[build-dependencies]
pyo3-build-config = "0.29"
