[package]
authors      = { workspace = true }
categories   = { workspace = true }
edition      = "2021"
homepage     = { workspace = true }
keywords     = { workspace = true }
license-file = { workspace = true }
name         = "oicana_node_native"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi        = "3.0.0"
napi-derive = "3.0.0"

oicana_export = { workspace = true, features = ["pdf", "png", "svg"] }
oicana_files  = { workspace = true, features = ["packed"] }
oicana_input  = { workspace = true }
oicana_world  = { workspace = true }

typst        = { workspace = true }
typst-pdf    = { workspace = true }
typst-render = { workspace = true }

dashmap    = { workspace = true }
once_cell  = { workspace = true }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid       = { workspace = true, features = ["v4"] }

[build-dependencies]
napi-build = "2"
