[package]
authors      = { workspace = true }
categories   = { workspace = true }
edition      = "2021"
homepage     = { workspace = true }
keywords     = { workspace = true }
license-file = { workspace = true }
name         = "oicana_node_native"
publish      = false
repository   = { workspace = true }
version      = "0.2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi        = "3.0.0"
napi-derive = "3.0.0"

oicana_ffi_core = { workspace = true }

[build-dependencies]
napi-build = "2"
