/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A blob with its metadata. */
export interface BlobWithMetadata {
  /** The byte content of the blob. */
  bytes: Uint8Array
  /** Metadata of the blob. */
  meta: string
}

export declare const enum CompilationMode {
  Production = 0,
  Development = 1,
}

/**
 * Compile the identified template with the given inputs.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function compileTemplate(
  template: string,
  jsonInputs: Record<string, string>,
  blobInputs: Record<string, BlobWithMetadata>,
  compilationMode: CompilationMode,
): string

/** Manually evict the comemo cache based on the configured cache age. */
export declare function evictCache(): void

/**
 * Export the given document
 *
 * Make sure to call `removeDocument` with the documentId afterwards, to free the memory.
 */
export declare function exportDocument(documentId: string, exportFormat: string): Buffer

/**
 * Load the source of the given file in the template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function getFile(template: string, file: string): Buffer

/**
 * Load the source of the given file in the template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function getSource(template: string, file: string): string

/**
 * Load all input definitions for the given template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function inputs(template: string): string

/**
 * Error string when a requested template is not registered yet. Call `[register_template]` before
 * trying to use the template through a different method.
 */
export const NOT_REGISTERED: string

/**
 * Register the given template. This will read the template files as a [`PackedTemplate`] and
 * compile it once with the given inputs. The Typst [`typst::World`] will be cached and reused for
 * subsequent calls to the other methods with the same template identifier.
 */
export declare function registerTemplate(
  template: string,
  files: Uint8Array,
  jsonInputs: Record<string, string>,
  blobInputs: Record<string, BlobWithMetadata>,
  compilationMode: CompilationMode,
): string

/** Remove the document from the cache. */
export declare function removeDocument(documentId: string): void

/**
 * Remove the world from the cache.
 *
 * The template will have to be registered again before it can be compiled again.
 */
export declare function removeWorld(templateId: string): void

/**
 * Set the global cache age for comemo cache eviction.
 *
 * Pass `null` or `undefined` to disable cache eviction completely.
 * Pass a number to set the maximum age threshold.
 *
 * # How Cache Aging Works
 *
 * - Each cache entry has an age counter
 * - Age increases by 1 during each eviction call
 * - Age resets to 0 when the entry is used (cache hit)
 * - Entries with age >= `max_age` are removed
 *
 * # Parameters
 *
 * * `max_age` - Maximum age threshold, or null/undefined to disable:
 *   - `null` or `undefined` - Disables cache eviction (cache never cleared)
 *   - `0` - Clears all cache after every compilation
 *   - `1` - Keeps only entries used since the last eviction
 *   - `n` - Keeps entries used within the last n evictions
 *
 * Default: 10
 */
export declare function setCacheEvictionAge(maxAge?: number | undefined | null): void
