/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A blob with its metadata. */
export interface BlobWithMetadata {
  /** The byte content of the blob. */
  bytes: Uint8Array
  /** Metadata of the blob. */
  meta: string
}

export declare const enum CompilationMode {
  Production = 0,
  Development = 1,
}

/**
 * Compile the identified template with the given inputs.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function compileTemplate(
  template: string,
  jsonInputs: Record<string, string>,
  blobInputs: Record<string, BlobWithMetadata>,
  compilationMode: CompilationMode,
): string

/**
 * Configure automatic cache eviction after each compilation.
 *
 * # Parameters
 *
 * `max_age` (start value: 10) - Maximum age threshold, or null to disable:
 *   - `undefined`/`null` - Disables cache eviction (cache never cleared)
 *   - `0` - Clears all cache entries with every eviction
 *   - `1` - Keeps only entries used since the last eviction
 *   - `n` - Keeps entries used within the last n evictions
 */
export declare function configureAutomaticCacheEviction(maxAge?: number | undefined | null): void

/**
 * Return the sizes (in points) of every page of a compiled document as a JSON
 * array of `{ "width": number, "height": number }`.
 */
export declare function documentPages(documentId: string): string

/**
 * Manually evict the comemo cache with the given age threshold.
 *
 * This directly calls the underlying eviction with the specified age,
 * regardless of the configured default age.
 */
export declare function evictCache(maxAge: number): void

/**
 * Export the given document
 *
 * `page_range` is a JSON object `{ "start"?: number, "end"?: number }` with
 * 0-based, inclusive bounds, or an empty string to export the whole document.
 *
 * Make sure to call `removeDocument` with the documentId afterwards, to free the memory.
 */
export declare function exportDocument(documentId: string, exportFormat: string, pageRange: string): Buffer

/**
 * Load the source of the given file in the template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function getFile(template: string, file: string): Buffer

/**
 * Load the source of the given file in the template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function getSource(template: string, file: string): string

/**
 * Return any compilation warnings produced for the given document, or `null`
 * if there were none. Warnings are cleared when the document is removed.
 */
export declare function getWarnings(documentId: string): string | null

/**
 * Load all input definitions for the given template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function inputs(template: string): string

/**
 * Error string when a requested template is not registered yet. Call `[register_template]` before
 * trying to use the template through a different method.
 */
export const NOT_REGISTERED: string

/**
 * Register the given template. This will read the template files as a [`PackedTemplate`] and
 * compile it once with the given inputs. The Typst [`typst::World`] will be cached and reused for
 * subsequent calls to the other methods with the same template identifier.
 */
export declare function registerTemplate(
  template: string,
  files: Uint8Array,
  jsonInputs: Record<string, string>,
  blobInputs: Record<string, BlobWithMetadata>,
  compilationMode: CompilationMode,
): string

/** Remove the document from the cache. */
export declare function removeDocument(documentId: string): void

/**
 * Remove the world from the cache.
 *
 * The template will have to be registered again before it can be compiled again.
 */
export declare function removeWorld(templateId: string): void

/**
 * Enable or disable JSON schema validation for the given template.
 *
 * When enabled (the default), JSON inputs are validated against their schemas
 * before compilation.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function setValidateInputs(template: string, validate: boolean): void
