/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A blob with its metadata. */
export interface BlobWithMetadata {
  /** The byte content of the blob. */
  bytes: Uint8Array
  /** Metadata of the blob. */
  meta: Record<string, string>
}

/**
 * Compile the identified template with the given inputs.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function compileTemplate(
  template: string,
  jsonInputs: Record<string, string>,
  blobInputs: Record<string, BlobWithMetadata>,
  exportFormat: ExportFormat,
): Buffer

/** The supported export formats of a template. */
export declare const enum ExportFormat {
  /**
   * Render the template into a png image.
   *
   * The image is not optimized for file size to speed up compiling.
   */
  Png = 0,
  /**
   * Render the template to a PDF file.
   *
   * The currently exported standard is PDF/A-3b
   */
  Pdf = 1,
}

/**
 * Load the source of the given file in the template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function getFile(template: string, file: string): Buffer

/**
 * Load the source of the given file in the template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function getSource(template: string, file: string): string

/**
 * Load all input definitions for the given template.
 *
 * Calling this method requires a previous call to [`register_template`] with the same template
 * identifier.
 */
export declare function inputs(template: string): string

/**
 * Error string when a requested template is not registered yet. Call `[register_template]` before
 * trying to use the template through a different method.
 */
export const NOT_REGISTERED: string

/**
 * Register the given template. This will read the template files as a [`PackedTemplate`] and
 * compile it once with the given inputs. The Typst [`typst::World`] will be cached and reused for
 * subsequent calls to the other methods with the same template identifier.
 */
export declare function registerTemplate(
  template: string,
  files: Uint8Array,
  jsonInputs: Record<string, string>,
  blobInputs: Record<string, BlobWithMetadata>,
  exportFormat: ExportFormat,
): Buffer
