//! This example generates C# bindings from the `oicana_csharp` project.

use interoptopus::util::NamespaceMappings;
use interoptopus::{Error, Interop};
use interoptopus_backend_csharp::CSharpVisibility;

fn main() -> Result<(), Error> {
    use interoptopus_backend_csharp::{Config, Generator};

    Generator::new(
        Config {
            class: "OicanaFfiInternal".to_string(),
            dll_name: "oicana_csharp".to_string(),
            namespace_mappings: NamespaceMappings::new("Oicana.Interop"),
            visibility_types: CSharpVisibility::ForceInternal,
            file_header_comment:
                "// Automatically generated by Interoptopus.\n#pragma warning disable 1591"
                    .to_string(),
            ..Config::default()
        },
        oicana_csharp::my_inventory(),
    )
    .write_file("./integrations/csharp/Oicana/Interop/OicanaFfiInternal.cs")?;

    Ok(())
}
