[package]
name = "oicana_csharp"
description = "Oicana integration for C#."
version = "0.9.0-rc.2"
publish = false
keywords = { workspace = true }
categories = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license-file = { workspace = true }
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
oicana_ffi_core = { workspace = true }
serde_json = { workspace = true }

interoptopus = { workspace = true }

[dev-dependencies]
interoptopus_backend_csharp = { workspace = true }

[lints]
workspace = true
