[package]
authors      = { workspace = true }
categories   = { workspace = true }
edition      = "2021"
homepage     = { workspace = true }
keywords     = { workspace = true }
license-file = { workspace = true }
name         = "oicana_java_native"
publish      = false
repository   = { workspace = true }
version      = "0.3.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.22"

oicana_ffi_core = { workspace = true }
