[package]
name = "oicana_php_native"
version = "0.3.0"
edition = "2024"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license-file = "LICENSE.md"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
name = "oicana_php_native"
crate-type = ["cdylib"]

[dependencies]
ext-php-rs = "0.15"

oicana_ffi_core = { workspace = true }

[lints]
workspace = true
