[package]
name = "oicana"
description = "Oicana for Rust - Dynamic PDF Generation with Typst."
keywords = { workspace = true }
categories = { workspace = true }
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license-file = { workspace = true }

[features]
default = ["pdf", "packed"]

packed    = ["oicana_files/packed"]
native    = ["oicana_files/native"]
preloaded = ["oicana_files/preloaded"]

pdf = ["dep:oicana_export", "oicana_export/pdf"]
png = ["dep:oicana_export", "oicana_export/png"]
svg = ["dep:oicana_export", "oicana_export/svg"]

[dependencies]
oicana_world    = { workspace = true }
oicana_files    = { workspace = true, default-features = false }
oicana_input    = { workspace = true }
oicana_template = { workspace = true }
oicana_export   = { workspace = true, default-features = false, optional = true }

typst = { workspace = true }

thiserror = { workspace = true }

[lints]
workspace = true
