name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-crates:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-stable--
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: check format
        run: cargo fmt --all -- --check
      - name: run clippy
        run: cargo clippy --workspace --all-targets --all-features -- -Dwarnings
      - name: check
        run: cargo check --workspace --all-features --all-targets

  test-crates:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-stable--
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: dtolnay/rust-toolchain@stable
      - name: run tests
        run: cargo test --workspace --all-targets --all-features

  check-node-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: integrations/node/oicana-node-native/yarn.lock
      - name: Native - Install dependencies
        run: yarn install
        working-directory: integrations/node/oicana-node-native
      - name: Wrapper - Install dependencies
        run: npm ci
        working-directory: integrations/node/oicana-node
      - name: Wrapper - lint
        run: npm run lint
        working-directory: integrations/node/oicana-node
      - name: Native - Format
        run: yarn format
        working-directory: integrations/node/oicana-node-native
      - name: Native - validate format was already correct
        run: |
          if [ -n "$(git status --porcelain './integrations/node/oicana-node-native/')" ]; then
            echo "::error::Run `yarn format` in integrations/node/oicana-node-native."
            git --no-pager diff --color=always './integrations/node/oicana-node-native/'
            exit 1
          fi

  check-browser-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: integrations/browser/oicana-browser/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: integrations/browser/oicana-browser
      - name: lint
        run: npm run lint
        working-directory: integrations/browser/oicana-browser

  check-csharp-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-stable--
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: dtolnay/rust-toolchain@stable
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: check format
        run: dotnet format --verify-no-changes
        working-directory: ./integrations/csharp
      - name: create bindings
        run: cargo run --example csharp_bindings -p oicana_csharp
      - name: format bindings
        run: dotnet format
        working-directory: ./integrations/csharp
      - name: validate no changes
        run: |
          if [ -n "$(git status --porcelain './integrations/csharp/')" ]; then
            echo "::error::Generated C# bindings are out of date! Update them and check in any changes."
            git --no-pager diff --color=always './generated/'
            exit 1
          fi

  build-csharp:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            lib: liboicana_csharp.so
          - os: macos-latest
            lib: liboicana_csharp.dylib
          - os: windows-latest
            lib: oicana_csharp.dll
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-stable--
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: dtolnay/rust-toolchain@stable
      - name: build oicana_csharp
        run: cargo build --release -p oicana_csharp
      - name: Upload liboicana_csharp
        uses: actions/upload-artifact@v4
        with:
          name: liboicana_csharp_${{ runner.os }}
          path: ./target/release/${{ matrix.lib }}
          if-no-files-found: error

  build-browser-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-stable--
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack
      - name: build browser wasm
        run: wasm-pack build --release --target web --scope oicana integrations/browser/oicana_browser_wasm
      - name: rename package
        run: jq '.name = "@oicana/browser-wasm"' package.json > tmp.json && mv tmp.json package.json
        working-directory: ./integrations/browser/oicana_browser_wasm/pkg
      - name: Upload browser-wasm
        uses: actions/upload-artifact@v4
        with:
          name: browser-wasm
          path: |
            ./integrations/browser/oicana_browser_wasm/pkg/oicana_browser_wasm**
            ./integrations/browser/oicana_browser_wasm/pkg/package.json
            ./integrations/browser/oicana_browser_wasm/pkg/README.md
          if-no-files-found: error

  build-node-native:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: integrations/node/oicana-node-native/yarn.lock
      - uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-stable--
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: yarn install
        working-directory: integrations/node/oicana-node-native
      - name: Build
        run: yarn build
        working-directory: integrations/node/oicana-node-native
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_native_${{ runner.os }}
          path: |
            integrations/node/oicana-node-native/node-native.*.node
          if-no-files-found: error
      - name: Format
        run: yarn format
        working-directory: integrations/node/oicana-node-native
      - name: Normalize line endings
        shell: bash
        run: git add --renormalize ./integrations/node/oicana-node-native/
      - name: validate no changes
        shell: bash
        run: |
          if [ -n "$(git status --porcelain './integrations/node/oicana-node-native/')" ]; then
            echo "::error::Generated JS bindings are out of date! Update them and check in any changes."
            git --no-pager diff --color=always './integrations/node/oicana-node-native/'
            exit 1
          fi

  build-tools:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        tool_config:
          - tool: "oicana-cli"
            path: "tools/oicana_cli"
            bin: "oicana"
          - tool: "test-compare"
            path: "tools/test_compare"
            bin: "test-compare"
        include:
          - os: windows-latest
            bin_ext: ".exe"
          - os: ubuntu-latest
            bin_ext: ""
          - os: macos-latest
            bin_ext: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ${{ runner.os }}-stable--${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-stable--
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - uses: dtolnay/rust-toolchain@stable
      - name: Build and install ${{ matrix.tool_config.tool }}
        run: cargo install --path ${{ matrix.tool_config.path }}
      - name: Upload CLI tool binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.tool_config.tool }}_${{ runner.os }}
          path: ~/.cargo/bin/${{ matrix.tool_config.bin }}${{ matrix.bin_ext }}
          if-no-files-found: error

  e2e-test-node-integration:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - build-tools
      - build-node-native
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: typship
      - name: Install local Typst Oicana package
        run: typship install local
        working-directory: ./integrations/typst
      - uses: ./.github/actions/install-tool
        with:
          tool: "oicana-cli"
          bin: "oicana"
      - uses: ./.github/actions/install-tool
        with:
          tool: "test-compare"
      - name: test e2e template
        run: oicana test
        working-directory: ./e2e-tests/template
      - name: pack e2e template
        run: oicana pack -n '{template}-x.y.z.zip'
        working-directory: ./e2e-tests/template
      - name: install node-native
        uses: actions/download-artifact@v4
        with:
          name: node_native_${{ runner.os }}
          path: ./integrations/node/oicana-node-native
      - name: Enable npm link in node-native
        run: npm link
        working-directory: ./integrations/node/oicana-node-native
      - name: install node integration
        run: |
          npm i
          npm link @oicana/node-native
        working-directory: ./integrations/node/oicana-node
      - name: test node integration
        run: npm run test
        working-directory: ./integrations/node/oicana-node
      - name: compare test output
        run: test-compare e2e-tests/template integrations/node/oicana-node/testOutput/

  e2e-test-browser-integration:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - build-tools
      - build-browser-wasm
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: typship
      - name: Install local Typst Oicana package
        run: typship install local
        working-directory: ./integrations/typst
      - uses: ./.github/actions/install-tool
        with:
          tool: "oicana-cli"
          bin: "oicana"
      - uses: ./.github/actions/install-tool
        with:
          tool: "test-compare"
      - name: test e2e template
        run: oicana test
        working-directory: ./e2e-tests/template
      - name: pack e2e template
        run: oicana pack -n '{template}-x.y.z.zip'
        working-directory: ./e2e-tests/template
      - name: install browser-wasm
        uses: actions/download-artifact@v4
        with:
          name: browser-wasm
          path: ./integrations/browser/oicana_browser_wasm/pkg
      - name: Enable npm link in browser-wasm
        run: npm link
        working-directory: ./integrations/browser/oicana_browser_wasm/pkg
      - name: install browser integration
        run: |
          npm i
          npm link @oicana/browser-wasm
        working-directory: ./integrations/browser/oicana-browser
      - name: test browser integration
        run: npm run test
        working-directory: ./integrations/browser/oicana-browser
      - name: compare test output
        run: test-compare e2e-tests/template integrations/browser/oicana-browser/testOutput/

  e2e-test-csharp-integration:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - build-tools
      - build-csharp
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - uses: taiki-e/install-action@v2
        with:
          tool: typship
      - name: Install local Typst Oicana package
        run: typship install local
        working-directory: ./integrations/typst
      - uses: ./.github/actions/install-tool
        with:
          tool: "oicana-cli"
          bin: "oicana"
      - uses: ./.github/actions/install-tool
        with:
          tool: "test-compare"
      - name: test e2e template
        run: oicana test
        working-directory: ./e2e-tests/template
      - name: pack e2e template
        run: oicana pack -n '{template}-x.y.z.zip'
        working-directory: ./e2e-tests/template
      - name: install csharp lib
        uses: actions/download-artifact@v4
        with:
          name: liboicana_csharp_${{ runner.os }}
          path: ./target/release/
      - name: test csharp integration
        run: dotnet test
        working-directory: ./integrations/csharp
      - name: compare test output
        run: test-compare e2e-tests/template integrations/csharp/Oicana.Test/bin/Debug/net8.0/e2e/

  e2e-test-cli:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs:
      - build-tools
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/install-tool
        with:
          tool: "oicana-cli"
          bin: "oicana"
      - uses: ./.github/actions/install-tool
        with:
          tool: "test-compare"
      - uses: taiki-e/install-action@v2
        with:
          tool: typship
      - name: Install local Typst Oicana package
        run: typship install local
        working-directory: ./integrations/typst
      - name: test e2e template
        run: oicana test
        working-directory: ./e2e-tests/template
      - name: compile e2e template with cli
        run: |
          oicana compile -o output -f png -n development.png --development
          oicana compile -o output -f png -n production.png -b development-blob=tests/input.txt -m development-blob=tests/cli/development-blob-meta.json -j development-json=tests/input.json
          oicana compile -o output -f png -n all-inputs.png -b development-blob=tests/input.txt -m development-blob=tests/cli/development-blob-meta.json -j development-json=tests/input.json -b default-blob=tests/input.txt -m default-blob=tests/cli/default-blob-meta.json -j default-json=tests/input.json -b both-blob=tests/input.txt -m both-blob=tests/cli/both-blob-meta.json -j both-json=tests/input.json
        working-directory: e2e-tests/template
      - name: compare test output
        run: test-compare e2e-tests/template e2e-tests/template/output

  typst-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-tytanic@v1
        with:
          tytanic-version: 0.3.0
      - uses: taiki-e/install-action@v2
        with:
          tool: typstyle
      - name: check style
        run: typstyle --check .
        working-directory: ./integrations/typst
      - name: Run test suite
        run: tt run
        working-directory: ./integrations/typst
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: typst-package-test-results
          path: |
            integrations/typst/tests/**/diff/*.png
            integrations/typst/tests/**/out/*.png
            integrations/typst/tests/**/ref/*.png
          retention-days: 5

  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.35.5

  validate-links:
    name: Check for dead links in docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-shiroa@v1
        with:
          shiroa-version: 0.3.1-rc3
      - name: serve docs
        run: |
          nohup shiroa serve book --mode static-html --workspace . > /tmp/shiroa.log 2>&1 &
          echo $! > /tmp/shiroa.pid
          sleep 15
        working-directory: docs
      - name: check for broken links
        run: npx linkinator http://localhost:25520 --recurse --skip https://www.npmjs.com/package/@oicana/browser
      - name: clean up
        if: always()
        run: |
          kill $(cat /tmp/shiroa.pid) || true
          echo "::: Shiroa Logs :::"
          cat /tmp/shiroa.log || true
      - name: check readme links
        run: npx linkinator README.md integrations/typst/README.md integrations/csharp/Oicana/Readme.md integrations/browser/oicana-browser/README.md
