name: publish npm @oicana/browser

on:
  workflow_dispatch:
  push:
    tags:
      - 'oicana_browser-v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  build-and-publish-wasm:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH: ${{ secrets.NPM_AUTH }}
      CRATE_DIR: oicana_browser_wasm
      LIB_NAME: oicana-browser-wasm
      SCOPE: oicana
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack
      - name: Build release
        run: wasm-pack build --release --target web --scope ${{ env.SCOPE }} integrations/browser/${{ env.CRATE_DIR }}
      - name: Copy License file
        run: cp LICENSE.md integrations/browser/$CRATE_DIR/pkg
      - name: rename package
        run: jq '.name = "@oicana/browser-wasm"' package.json > tmp.json && mv tmp.json package.json
        working-directory: integrations/browser/${{ env.CRATE_DIR }}/pkg
      - name: Pack
        run: npm pack
        working-directory: integrations/browser/${{ env.CRATE_DIR }}/pkg
      - name: version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
        working-directory: integrations/browser/${{ env.CRATE_DIR }}/pkg
      - uses: actions/upload-artifact@v7
        with:
          name: "oicana-browser-wasm-${{ steps.version.outputs.version }}.tgz"
          path: integrations/browser/${{ env.CRATE_DIR }}/pkg/${{ env.LIB_NAME }}-*.tgz
      - name: Publish
        run: |
          name=$(node -p "require('./package.json').name")
          version=$(node -p "require('./package.json').version")
          
          echo "Checking if $name@$version already exists:"
          if npm view $name@$version > /dev/null; then
            echo "Version $version already exists on npmjs. Not publishing."
            exit 0
          else
            echo "Version $version not found on npmjs. Proceeding to publish..."
          fi

          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          if echo $version | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            npm publish --access public
          elif echo $version | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+";
          then
            npm publish --access public --tag next
          fi
        working-directory: integrations/browser/${{ env.CRATE_DIR }}/pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-and-publish-wrapper:
    runs-on: ubuntu-latest
    needs:
      - build-and-publish-wasm
    env:
      NPM_AUTH: ${{ secrets.NPM_AUTH }}
      LIB_NAME: browser
      SCOPE: oicana
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm i
        working-directory: integrations/browser/oicana-browser
      - name: Build
        run: npm run build
        working-directory: integrations/browser/oicana-browser
      - name: Pack
        run: npm pack
        working-directory: integrations/browser/oicana-browser
      - name: version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
        working-directory: integrations/browser/oicana-browser
      - uses: actions/upload-artifact@v7
        with:
          name: "oicana-browser-${{ steps.version.outputs.version }}.tgz"
          path: integrations/browser/oicana-browser/${{ env.SCOPE }}-${{ env.LIB_NAME }}-*.tgz
      - name: Publish
        run: |
          name=$(node -p "require('./package.json').name")
          version=$(node -p "require('./package.json').version")
          
          echo "Checking if $name@$version already exists:"
          if npm view $name@$version > /dev/null; then
            echo "Version $version already exists on npmjs. Not publishing."
            exit 0
          else
            echo "Version $version not found on npmjs. Proceeding to publish..."
          fi

          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          if echo $version | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            npm publish --access public
          elif echo $version | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+";
          then
            npm publish --access public --tag next
          fi
        working-directory: integrations/browser/oicana-browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
