[package]
name = "oicana-browser-wasm"
version = "0.6.0-rc.1"
description = "Oicana integration for WASM in the browser."
publish = false
keywords = { workspace = true }
categories = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = "PolyForm-Noncommercial-1.0.0"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
oicana_ffi_core = { workspace = true }
oicana_world = { workspace = true }

wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
js-sys = { workspace = true }
console_log = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "js"] }

[lints]
workspace = true

[package.metadata.wasm-pack.profile.debug]
wasm-opt = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-reference-types", "--enable-sign-ext", "--enable-nontrapping-float-to-int", "--enable-simd"]
